### ISSUE TITLE
Added replacing of hexadecimal chars in strings

### ISSUE THREAD

**Issue by realtebo** [mindedsecurity/JStillery#23]
Just a snippet

```
'\x4d\x6f\x75\x73\x65\x4d\x6f\x76\x65\x6d\x65\x6e\x74': {
                        '\x66\x69\x65\x6c\x64\x73': {
                            '\x74\x69\x6d\x65': {
                                '\x74\x79\x70\x65': p7b,
                                '\x69\x64': +X0x.y1B
                            },
                            '\x78': {
                                '\x74\x79\x70\x65': I0x.w3y(+c0x.i0B),
                                '\x69\x64': X0x.I7B * I0x.f5l
                            },
                            '\x79': {
                                '\x74\x79\x70\x65': I0x.r3y(+c0x.i0B),
                                '\x69\x64': +c0x.b5B
                            },
                            '\x77\x78': {
                                '\x74\x79\x70\x65': I0x.w3y(+c0x.i0B),
                                '\x69\x64': I0x.x5l
                            },
                            '\x77\x79': {
                                '\x74\x79\x70\x65': I0x.w3y(c0x.i0B - I0x.J5l),
                                '\x69\x64': +G0x.f6B
                            }
                        }
                    },

```

It could be very usefull to do replace of hex chars to ascii equivalent.

Be aware, if you will try, to avoid replacing of escaped one !

So \x3a need to be replaced, but \\x3a not !

**Comment by wisec** [comment]
@realtebo the code you want to deobfuscate *must* be syntactically correct.
if we launch your code (without the trailing comma) there will be an error printed in console:

```
 "Error: Line 1: Unexpected token :↵    at ErrorHandler.constructError 
(https://mindedsecurity.github.io/jstillery/static/js/jstiller.browser.js:21430:22)↵    at 
ErrorHandler.createError (https://mindedsecurity.github.io/jstillery/static/js/jstiller.browser.js:21446:27)↵    at Parser.unexpectedTokenError 
(https://mindedsecurity.github.io/jstillery/static/js/jstiller.browser.js:18411:39)↵    at 
Parser.throwUnexpectedToken 
(https://mindedsecurity.github.io/jstillery/static/js/jstiller.browser.js:18421:21)↵    at 
Parser.consumeSemicolon (https://mindedsecurity.github.io/jstillery/static/js/jstiller.browser.js:18716:23)↵    at Parser.parseExpressionStatement 
(https://mindedsecurity.github.io/jstillery/static/js/jstiller.browser.js:20065:15)↵    at 
Parser.parseStatement (https://mindedsecurity.github.io/jstillery/static/js/jstiller.browser.js:20518:35)↵    at Parser.parseStatementListItem 
(https://mindedsecurity.github.io/jstillery/static/js/jstiller.browser.js:19809:31)↵    at Parser.parseBlock (https://mindedsecurity.github.io/jstillery/static/js/jstiller.browser.js:19821:30)↵    at 
Parser.parseStatement (https://mindedsecurity.github.io/jstillery/static/js/jstiller.browser.js:20523:39)"
```
Which is an error triggered by Esprima and it's due to the fact that an literal object is not correct JS code.
On the contrary if you surround it with parenthesis or assign it to a variable, Esprima will be happy and JStillery will do its magic.
 
You can try the following [Snippet](https://mindedsecurity.github.io/jstillery/#KCU3QiUwQSUyMCUyMCclNUN4NGQlNUN4NmYlNUN4NzUlNUN4NzMlNUN4NjUlNUN4NGQlNUN4NmYlNUN4NzYlNUN4NjUlNUN4NmQlNUN4NjUlNUN4NmUlNUN4NzQnJTNBJTIwJTdCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJyU1Q3g2NiU1Q3g2OSU1Q3g2NSU1Q3g2YyU1Q3g2NCU1Q3g3MyclM0ElMjAlN0IlMEElMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAnJTVDeDc0JTVDeDY5JTVDeDZkJTVDeDY1JyUzQSUyMCU3QiUwQSUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCclNUN4NzQlNUN4NzklNUN4NzAlNUN4NjUnJTNBJTIwcDdiJTJDJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJyU1Q3g2OSU1Q3g2NCclM0ElMjAlMkJYMHgueTFCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTJDJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJyU1Q3g3OCclM0ElMjAlN0IlMEElMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAnJTVDeDc0JTVDeDc5JTVDeDcwJTVDeDY1JyUzQSUyMEkweC53M3koJTJCYzB4LmkwQiklMkMlMEElMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAnJTVDeDY5JTVDeDY0JyUzQSUyMFgweC5JN0IlMjAqJTIwSTB4LmY1bCUwQSUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCclNUN4NzknJTNBJTIwJTdCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJyU1Q3g3NCU1Q3g3OSU1Q3g3MCU1Q3g2NSclM0ElMjBJMHgucjN5KCUyQmMweC5pMEIpJTJDJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJyU1Q3g2OSU1Q3g2NCclM0ElMjAlMkJjMHguYjVCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTJDJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJyU1Q3g3NyU1Q3g3OCclM0ElMjAlN0IlMEElMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAnJTVDeDc0JTVDeDc5JTVDeDcwJTVDeDY1JyUzQSUyMEkweC53M3koJTJCYzB4LmkwQiklMkMlMEElMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAnJTVDeDY5JTVDeDY0JyUzQSUyMEkweC54NWwlMEElMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlMkMlMEElMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAnJTVDeDc3JTVDeDc5JyUzQSUyMCU3QiUwQSUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCclNUN4NzQlNUN4NzklNUN4NzAlNUN4NjUnJTNBJTIwSTB4LnczeShjMHguaTBCJTIwLSUyMEkweC5KNWwpJTJDJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJyU1Q3g2OSU1Q3g2NCclM0ElMjAlMkJHMHguZjZCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTBBJTdEKQ==) :

```
({
  '\x4d\x6f\x75\x73\x65\x4d\x6f\x76\x65\x6d\x65\x6e\x74': {
                        '\x66\x69\x65\x6c\x64\x73': {
                            '\x74\x69\x6d\x65': {
                                '\x74\x79\x70\x65': p7b,
                                '\x69\x64': +X0x.y1B
                            },
                            '\x78': {
                                '\x74\x79\x70\x65': I0x.w3y(+c0x.i0B),
                                '\x69\x64': X0x.I7B * I0x.f5l
                            },
                            '\x79': {
                                '\x74\x79\x70\x65': I0x.r3y(+c0x.i0B),
                                '\x69\x64': +c0x.b5B
                            },
                            '\x77\x78': {
                                '\x74\x79\x70\x65': I0x.w3y(+c0x.i0B),
                                '\x69\x64': I0x.x5l
                            },
                            '\x77\x79': {
                                '\x74\x79\x70\x65': I0x.w3y(c0x.i0B - I0x.J5l),
                                '\x69\x64': +G0x.f6B
                            }
                        }
                    }
})
```

Which is transformed as you need.
Thanks!
